config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  root 'welcome#index'

  get 'about' => 'welcome#about'

  get 'contact' => 'welcome#contact'

  get 'welcome/blog'

  get 'podcasts' => 'welcome#podcasts'

  get 'gallery' => 'welcome#gallery'

  get 'knitting' => 'welcome#knitting'

  get 'lj007670' => 'blogs#new'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :avatar)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def blog
  end

  def podcasts
  end

  def gallery
    @gallery_images = ["portrait.jpg","hand","kit.jpg","doc1.jpg","stained-glass.jpg","f-trees.jpg","ghost.jpg","armchair.jpg","balloon.jpg"]
  end

  def knitting
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.text_area :body, placeholder: "Body", class: "form-control" %>
  </div>
  <div class= "form-group">
    <%= f.label "Image" %><br>
    <%= f.text_area :avatar %>
  </div>
  <div class="actions form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<% if notice != nil %>
  <div class="alert alert-danger" role="alert">
   <p id="notice"><%= notice %></p>
  </div>
<% end %>

<h1>Listing Blogs</h1>

  <div class="row">
    <% @blogs.each do |blog| %>
      <div class="col-md-4">
        <div class="panel panel-success">
          <div class="panel heading"><h2><%= blog.title %></h2></div>
          <div class="panel body">
            <% if blog.avatar_file_name != nil %>
            <p><%= image_tag blog.avatar.url(:thumb) %></p>
          <% else %>
          <% if blog.avatar_file_name != nil %>
   <%= image_tag blog.avatar.url(:medium), class: "img-responsive" %>
            <p><%= image_tag "missing-dest-image.png" %></p>
            <% end %>
          <% end %>
            <p><%= blog.body[0..250] %></p>
            <p><%= link_to "READ MORE", blog %></P>
          </div>
          <div class="panel footer">
          <%= link_to 'Show', blog %>
          <%= link_to 'Edit', edit_blog_path(blog) %>
          <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p> <%= image_tag @blog.avatar.url(:medium) %></p>


<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RosalindGanymede</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>
<nav id="nav" class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       <li><a href="https://leilajacob.wordpress.com/" target="_blank">Blog</a></li>
<!--         <li><%= link_to "Podcasts", podcasts_path %></li> -->
        <li><%= link_to "About", about_path %></li>
<!--         <li><%= link_to "Contact", contact_path %></li> -->
<!--         <li><%= link_to "Gallery", gallery_path %></li> -->
        <li><%= link_to "Knitting", knitting_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<p id="progress"><strong><a href="http://nanowrimo.org/participants/rosalind-as-ganymede/novels" target="_blank">NaNoWriMo</a> Progress: </strong></p>

<p><div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
    <span class="sr-only">0% Complete</span>
  </div>
</div></p>

<div class="jumbotron">
  <h1>Rosalind As Ganymede</h1>
</div>

  <div class = "container">
  <%= yield %>

      <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  </body>
</html>

  <div class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
    <div class="container">
      <div class="navbar-text">
        <a href="https://instagram.com/leila.jacob/" target="_blank"><span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-instagram fa-stack-1x"></i>
        </span>
        <a href="https://www.pinterest.com/asganymede/" target="_blank"><span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-pinterest fa-stack-1x"></i>
        </span>
        <a href="https://twitter.com/leila_jacob" target="_blank"><span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-twitter fa-stack-1x"></i>
        </span>
        <a href="https://www.youtube.com/channel/UCdU1vd_pVw83Yec1FfdgTyQ?view_as=public" target="_blank"><span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-youtube fa-stack-1x"></i>
        </span>
        <a href="http://leilajacob.deviantart.com/" target="_blank"><span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-deviantart fa-stack-1x"></i>
        </span>
        <a href="http://rosalindasganymede.tumblr.com/" target="_blank"><span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-tumblr fa-stack-1x"></i>
        </span>
        <a href="https://github.com/leilajacob" target="_blank"><span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-github-square fa-stack-1x"></i>
        </span>
        <!-- <a href=""><span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-slack fa-stack-1x"></i>
        </span> -->
        <a href="https://www.linkedin.com/profile/view?id=AAMAABWcluUB2lmuExk-XtJMBws1Y2c-i4gW9sw&trk=hp-identity-name" target="_blank"><span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-linkedin fa-stack-1x"></i>
        </span>
      </div>
    </div>
  </div>

  <footer>
  <div class='container'>
    <ul class="nav nav-pills">
    </ul>
  </div>
</footer>
<script src='//railsgirls.com/assets/bootstrap.js'></script>

      


</body>
</html>

app/views/welcome/about.html.erb
<div class="row">
	<div class="col-md-6">
		<div id="panel" class="panel panel-default">
			<div><p id="panel-image"><%= image_tag "about.jpg", width: 300, class: "img-responsive" %></p><p id="contact-body">Pictured above, is me, Leila. I’m nineteen and have had this blog for eight years. It’s gone through a lot of phases. It started out as a blog about the 80% fictional “adventures” of my alter-ego Sheila. She was a paper doll. So I guess, strap in?</p></div>
		</div>
	</div>
	<div class="col-md-6">
		<div id="panel" class="panel panel-default">
			<div><p id="panel-image"><%= image_tag "rosalind.jpg", width: 300, class: "img-responsive" %></p><p id="contact-body">This is “Rosalind as Ganymede.” It’s just a dumb Shakespeare reference I used when this was briefly a street fashion blog. I really liked menswear inspired fashion for a week several years ago, and now people just think my name’s Rosalind.</p></div>
		</div>
	</div>
</div> 

app/views/welcome/contact.html.erb
 <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="panel panel-default">
            <div id="panel" class="panel-body">
          <img id="contact" src="assets/images/profile.jpg" width="200" alt="contact">
            </div>
          </div>
        </div>
        <div class="col-md-4">
            <ul>
              <li id="b"><a class="btn btn-primary btn-lg" href="https://www.facebook.com/profile.php?id=100010390513573" target="_blank">Facebook <span class="glyphicon glyphicon-thumbs-up"></span></a></l1>
              <li id="b"><a class="btn btn-primary btn-lg" href="mailto:leilajacob@me.com" target="_blank">Email <span class="glyphicon glyphicon-envelope"></span></a></li>
              <li id="b"><a class="btn btn-primary btn-lg" href="https://twitter.com/actualchocolate" target="_blank">Twitter</a></li>
              <li id="b"><a class="btn btn-primary btn-lg" href="https://www.pinterest.com/actualchocolate/" target="_blank">Pinterest</a></li>
            </ul>
        </div>
        <div class="col-md-4">
          <div class="panel panel-default">
            <div id="panel" class="panel-body">
              <img id="easel" src="assets/images/easel.jpg" alt="easel">
            </div>
          </div>
        </div>
      </div>

app/views/welcome/gallery.html.erb
<div class="row">
	<%= @gallery_images.shuffle.each do |image| %>
	<div class="col-md-6">
		<div id="panel" class="table responsive">
			<div class="panel-body"><%= image_tag image, class: "img-responsive" %></div>
		</div>
	</div>
	<% end %>
</div>

app/views/welcome/index.html.erb
<div class="row">
	<p><%= image_tag "frames.jpg", class: "frames" %></p>
</div>

app/views/welcome/knitting.html.erb
<div class="row">
	<div class="col-md-4">
		<div id="panel" class="panel panel-default">
			<div><p id="panel-image"><a href="http://www.amazon.com/gp/product/1936096765/ref=s9_simh_gw_p14_d0_i1?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=desktop-1&pf_rd_r=1WYX4EEKW5W21HBE4431&pf_rd_t=36701&pf_rd_p=2079475242&pf_rd_i=desktop" target="_blank"><h3>60 Quick Luxury Knits</h3></p><%= image_tag "60-quick.jpg", width: 300, class: "img-responsive" %><p id="contact-body"></p></div>
		</div>
	</div>
	<div class="col-md-4">
		<div id="panel" class="panel panel-default">
			<div><p id="panel-image"><a href="http://www.ravelry.com/designers/leila-jacob" target="_blank"><h3>My Patterns</h3></p><%= image_tag "blue-scarf.jpg", width: 300, class: "img-responsive" %><p id="contact-body"></p></div>
		</div>
	</div>
	<div class="col-md-4">
		<div id="panel" class="panel panel-default">
			<div><p id="panel-image"><a href="https://leilajacob.wordpress.com/category/knitting-2/" target="_blank"><h3>Knitting Blog</h3></p><%= image_tag "knitting-blog.jpg", width: 300, class: "img-responsive" %><p id="contact-body"></p></div>
		</div>
	</div>
</div> 

app/views/welcome/podcasts.html.erb
<div class="jumbotron">
	<h1>Welcome#podcasts</h1>
</div>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>